### ISSUE TITLE
HS-PGA (Hidradenitis Suppurativa Physician Global Assessment):

### ISSUE THREAD

**Issue by DBartlettHP** [billdenney/hidradenitis#4]
- A 6-point scale that assesses overall disease severity
- Scores range from 0 (clear) to 5 (very severe)
- Scoring is based on the physician's overall assessment of the patient's HS, considering factors such as the number and size of lesions, the extent of inflammation, and the presence of scarring or sinus tracts

Output will be binary for if this response is achieved or not.

**Comment by billdenney** [comment]
If this is only the 0 to 6 score, then it may not need coding in the package.  If it includes other parameters, then let's keep it in.

**Comment by DBartlettHP** [comment]
|              | Abscesses + Draining fistulas | Inflammatory Nodules     | Non-inflammatory nodules |
| :---        |    :----:   |          ---: |          ---: |
| Clean (1) | 0 | 0 | 0 |
| Minimal (2) | 0 | 0 | > 0 |
| Mild (3) | 0 | 1 - 4 | |
| Mild (3) | 1 | 0 | |
| Moderate (4) | 0 | $\geq$ 5 | |
| Moderate (4) | 1 | $\geq$ 1 | |
| Moderate (4) | 2 - 5 | < 10 | |
| Severe (5) | 2 - 5 | $\geq$ 10 | |
| Very Severe (6) | > 5 | | |

**Comment by billdenney** [comment]
Completed previously
