### ISSUE TITLE
IHS4 (International Hidradenitis Suppurativa Severity Score System):

### ISSUE THREAD

**Issue by DBartlettHP** [billdenney/hidradenitis#5]
- A numerical scoring system that assesses HS severity based on lesion counts
- The score is calculated by summing the following components:
  1. Number of nodules (multiplied by 1)
  2. Number of abscesses (multiplied by 2)
  3. Number of draining tunnels (multiplied by 4)
- Scores can range from 0-3 (mild), 4-10 (moderate), 11 and on (severe) with higher scores indicating more severe disease

Output will be a numerical value.

**Comment by billdenney** [comment]
It's not clear why this scale is bounded to a maximum of 39.  For example, what if someone has 10 draining tunnels?  Can you please describe why it is bounded at the top?

**Comment by DBartlettHP** [comment]
This may have been a misinformation on my side from looking at specific data with a highest value at 39. Perhaps it would be best to state any value higher than 11 would refer to the most severe.

**Comment by billdenney** [comment]
That makes sense.  And, having a method to cast to descriptions like "mild", "moderate", and "severe" will be helpful.

For all the created, user-facing functions, please include an @references section in the documentation to clarify where the logic of the function came from.

**Comment by billdenney** [comment]
Completed in https://github.com/billdenney/hidradenitis/pull/8
