### ISSUE TITLE
HiSQOL (Hidradenitis Suppurativa Quality of Life):

### ISSUE THREAD

**Issue by DBartlettHP** [billdenney/hidradenitis#6]
- A patient-reported outcome measure that assesses the impact of HS on quality of life
- Consists of 17 items across 4 domains: symptoms, daily activities, psychosocial, and treatment
- Each item is scored on a 5-point scale (0-4), with higher scores indicating greater impact
- The total score is calculated by summing the scores for all items and ranges from 0 to 68
- Higher total scores indicate a greater impact of HS on quality of life

Output will be a numerical value.

**Comment by billdenney** [comment]
Completed previously
